Hero section
777Roma777/team-project pull request #4
Opened 2023-04-07 10:18 UTC by bgirlalma

2023-04-07 18:13 UTC, 777Roma777 commented on src/css/hero.css
> +  @media (min-device-pixel-ratio), (min-resolution: 102dpi), (min-resolution: 2dppx) {
в ratio пропущено значення 2
Повинно бути так  (min-device-pixel-ratio: 2)

2023-04-07 18:15 UTC, 777Roma777 commented on src/css/hero.css
> +  .buy-now-button {
не забуваємо додавати плавні переходи, за допомогою цих рядків на всі кнопки і модалки(якщо є):
transition-property: color;
  transition-duration: 250ms;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);

2023-04-07 18:22 UTC, 777Roma777 commented on src/css/hero.css
> +.hero-section {
переробити hero секцію, спробуй якось викорастити такий код  в цій секції
background-size: cover;
    background-image: linear-gradient(180deg,rgba(17,17,17,0) 0%,rgba(17,17,17,.4) 100%),url(../img/Hero/chocolate-mob-1x.jpg);
    padding-top: 381px;

2023-04-07 18:24 UTC, 777Roma777 commented on src/partials/hero.html
> +        <div class="scroll-wrapper">
при ховері не на кружечок, а на сам текст Scroll down, зникає стрілочка біла, пофіксити, можливо десь спільний контейнер створити або не туди ховер ефект підставила

2023-04-07 18:25 UTC, 777Roma777 commented on src/partials/hero.html
> +<!DOCTYPE html>
також прописати
 <section>
 твій код
 </section>
 і видалити зі свого хтмл доктайп і всі підключення, вони є в індексу

2023-04-07 18:26 UTC, bgirlalma commented on src/css/hero.css
> +.hero-section {
Padding не вариант, оно просто схлопывается и всё. И нам говорили на занятиях, что если слишком большой марджин или паддинг, то нужно днлать через позиционирование

2023-04-07 18:28 UTC, bgirlalma commented on src/partials/hero.html
> +        <div class="scroll-wrapper">
я прописала и туда и туда ховер. текст и кнопка у меня в линке, я прописала, что когда линка при ховере нужно чтобы менялся текст и текста и кнопки(бэкграунд и цвет иконки)

2023-04-07 19:48 UTC, bgirlalma reviewed
пофиксила

2023-04-08 04:39 UTC, Michael-Zhinchyn approved these changes

2023-04-08 04:40 UTC, Michael-Zhinchyn commented on src/css/styles.css
>  @import url('./vite-promo.css');
Для чого це тут? :)

2023-04-08 04:41 UTC, Michael-Zhinchyn commented on src/index.html
>        <h1>Lorem ipsum dolor sit amet.</h1>
lorem ? :)

2023-04-08 14:44 UTC, bgirlalma commented on src/css/styles.css
>  @import url('./vite-promo.css');
я не знаю. Это не моё

2023-04-08 14:45 UTC, bgirlalma commented on src/index.html
>        <h1>Lorem ipsum dolor sit amet.</h1>
и это не я писала

2023-04-08 15:19 UTC, 777Roma777 commented on src/index.html
>        <h1>Lorem ipsum dolor sit amet.</h1>
це зі старого сайту залишилось, просто прибрати потрібно все лишнє

2023-04-08 15:20 UTC, 777Roma777 commented on src/css/styles.css
>  @import url('./vite-promo.css');
Такс, тут ми прибираємо import vite promo, бо це зразок і додаємо сюди
@import url('./hero.css');

2023-04-08 15:23 UTC, 777Roma777 requested changes
заміна підключення стилів да hmtl

2023-04-10 18:46 UTC, 777Roma777 approved these changes

2023-04-10 18:48 UTC, merged