Footer
777Roma777/team-project pull request #5
Opened 2023-04-08 11:16 UTC by falcon777x

Its only needed to set correct address  to SVG. And we need to be sure that anchor links ( id ) works corect.

2023-04-08 15:35 UTC, 777Roma777 commented on src/partials/footer.html
> +			<ul class="footer-contacts">
я б тут замість ul використав div.
потім h3 із заголовком.
потім ul і 2 li з телефоном і поштою

2023-04-08 15:36 UTC, 777Roma777 requested changes
загалом, чудова робота, змінити тільки трішки список з адресою і телефоном і робота прийнята

2023-04-09 09:57 UTC, falcon777x commented
Hi. Can you check my last version 3.1 (7afab71). 
PS. Writing in english becouse  I do not have UKR keyboard

2023-04-09 10:11 UTC, 777Roma777 commented on src/partials/footer.html
> +<section class="footer-color">
додав секцію, бо не розширювався бекграунд при зміні розміру дисплею. А так, чудова робота!

2023-04-09 10:11 UTC, 777Roma777 approved these changes
Вніс сам деякі зміни

2023-04-09 10:16 UTC, merged